// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

// import 'firebase_options.dart';

// // ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC630-YmZDFQYltw1QKfmI6HFd-q_DIf2c',
    appId: '1:394343931902:web:b60404f7218fb8713faaaf',
    messagingSenderId: '394343931902',
    projectId: 'flutterauth-899d5',
    authDomain: 'flutterauth-899d5.firebaseapp.com',
    storageBucket: 'flutterauth-899d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8D6NRe_XBUiuvDN-qBRmjAJuWkRNRvM',
    appId: '1:394343931902:android:e93aedf92a7070f53faaaf',
    messagingSenderId: '394343931902',
    projectId: 'flutterauth-899d5',
    storageBucket: 'flutterauth-899d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyRHnBX7ExS_bSS_HvVtTBdqbKK2EWhbM',
    appId: '1:394343931902:ios:cb70ead6a8a4c2693faaaf',
    messagingSenderId: '394343931902',
    projectId: 'flutterauth-899d5',
    storageBucket: 'flutterauth-899d5.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyRHnBX7ExS_bSS_HvVtTBdqbKK2EWhbM',
    appId: '1:394343931902:ios:cb70ead6a8a4c2693faaaf',
    messagingSenderId: '394343931902',
    projectId: 'flutterauth-899d5',
    storageBucket: 'flutterauth-899d5.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC630-YmZDFQYltw1QKfmI6HFd-q_DIf2c',
    appId: '1:394343931902:web:a3daa46e45ab254a3faaaf',
    messagingSenderId: '394343931902',
    projectId: 'flutterauth-899d5',
    authDomain: 'flutterauth-899d5.firebaseapp.com',
    storageBucket: 'flutterauth-899d5.firebasestorage.app',
  );
}
