// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

// import 'firebase_options.dart';

// // ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1E0Kw1QPZFA-ioPFg7hzO4FUbycpd8m8',
    appId: '1:8842383345:web:f0df5a0084648317eb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    authDomain: 'flutterauth-7deca.firebaseapp.com',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Yeac6TRt4PJ_6QWV7tFNVKXlohDCJgI',
    appId: '1:8842383345:android:bf5f02e5690530ebeb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCSBLXhtcsyEQnCYjiJ8pF0qPu4N535WQ',
    appId: '1:8842383345:ios:4b38f1d0f80da39beb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
    iosClientId: '8842383345-fsta82es6nnq0o60gug3ogb8lrbeqmid.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCSBLXhtcsyEQnCYjiJ8pF0qPu4N535WQ',
    appId: '1:8842383345:ios:4b38f1d0f80da39beb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
    iosClientId: '8842383345-fsta82es6nnq0o60gug3ogb8lrbeqmid.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1E0Kw1QPZFA-ioPFg7hzO4FUbycpd8m8',
    appId: '1:8842383345:web:0e74af81d91d65cfeb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    authDomain: 'flutterauth-7deca.firebaseapp.com',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
  );

}